upstream webapp {
  server webapp:3000;
}
upstream backend {
  server backend:4000;
}
upstream prometheus {
  server prometheus:9090;
}
upstream grafana {
  server grafana:3000;
}
server {
  listen 80;
  server_name linguaflow1.duckdns.org;
  return 301 https://$host$request_uri;
}
server {
  listen 443 ssl;
  server_name linguaflow1.duckdns.org;

  ssl_certificate /etc/letsencrypt/live/linguaflow1.duckdns.org/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/linguaflow1.duckdns.org/privkey.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers HIGH:!aNULL:!MD5;

  location /api/ {
    proxy_pass http://backend/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
  location /prometheus/ {
    proxy_pass http://prometheus/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
  location / {
    proxy_pass http://webapp;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
