upstream webapp {
  server webapp:3000;
}
upstream backend {
  server backend:4000;
}
upstream prometheus {
  server prometheus:9090;
}
upstream grafana {
  server grafana:3000;
}
server {
  listen 80;
  location /api/ {
    proxy_pass http://backend/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
  location /prometheus/ {
    proxy_pass http://prometheus/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
  location /grafana/ {
    proxy_pass http://grafana/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
  }
  location / {
    proxy_pass http://webapp;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
